### ISSUE TITLE
大小写

### ISSUE THREAD

**Issue by d5d** [hit-computer/SC-LSTM#1]
DATE文件夹中TrainingData_Keywords.txt=====》需要改成TrainingData_keywords.txt才能运行。

**Comment by hit-computer** [comment]
谢谢提醒 :)

**Comment by d5d** [comment]
root@11:~/SC-LSTM# python train.py
Traceback (most recent call last):
  File "train.py", line 226, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 43, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "train.py", line 188, in main
    kwd_voc = cPickle.load(open('kwd_voc.pkl','r'))
IOError: [Errno 2] No such file or directory: 'kwd_voc.pkl'
root@27:~/SC-LSTM# python train.py
Traceback (most recent call last):
  File "train.py", line 226, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 43, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "train.py", line 188, in main
    kwd_voc = cPickle.load(open('kwd_voc.pkl','r'))
IOError: [Errno 2] No such file or directory: 'kwd_voc.pkl'
root@27:~/SC-LSTM# python train.py
Traceback (most recent call last):
  File "train.py", line 226, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 43, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "train.py", line 188, in main
    kwd_voc = cPickle.load(open('kwd_voc.pkl','r'))
IOError: [Errno 2] No such file or directory: 'kwd_voc.pkl'
root@11:~/SC-LSTM#



更新以后有错误。

**Comment by hit-computer** [comment]
我刚刚运行了一下最新版的程序没有问题啊，你是不是在运行 `train.py` 之前没有先运行 `Preprocess.py` 啊

**Comment by d5d** [comment]
抱歉，果然是没运行Preprocess.py。谢谢您的回复。
